### ISSUE TITLE
couldn't find the new *.xml file that the code expected to produce

### ISSUE THREAD

**Issue by gokceay** [roboticsleeds/mujoco_ur5_model#3]
Hi,
I tried to use the code you provided, and I couldn't produce a new *.xml file. After getting the new xml file, I planned to change the code for my xml file. Could you help me regarding this issue?

**Comment by rpapallas** [comment]
Hi,

You get an error? How do you supply the input file name? Is the filename correct?

**Comment by gokceay** [comment]
Hi, thanks a lot for your fast reply :)  No, I don't get an error, I used the example.xml file as as file and giving the path as /pathtofile/example.xml after this my script is running without an error but I couldn't find edited example.xml or any other produced xml file

**Comment by rpapallas** [comment]
I see. The idea is that the script uses an **existing** XML file to update the robot model and not to generate an entirely new one. So in your example, if you specify test.xml then you should have an existing file test.xml with the robot model that the script will basically “copy” and update the required values and then save it to disk. In this repo we do provide this test.xml file but as robot.xml under include directory.

**Comment by gokceay** [comment]
Before I tried to use xml example.xml after running the code, I simulate in mujoco simulator and couldn't see the change, also compared the robot.xml before and after running the script, I cannot see any change on the example.xml file :( I tried with different angles. But the thing is the code is asking for 6 angles, but there is 3 joints defined in the example.xml

**Comment by rpapallas** [comment]
So as I mention in the README file, this model does not use joints for UR5, is a static model. Meaning there are no joints for UR5. The three joints you see in the model is the base (mobile base) joints. The script asks 6 joints and updates the bodies quaternions (bodies orientation). We are planning at some point to include joints for the UR5.

Now, the way to use this script is to do the following:
Move the `set_ur5_joints.py` script in `include` directory. 

Run:  `python3 set_ur5_joints.py`

You will be asked for the UR5's 6 joint values in degrees as they appear on the UR5 screen. Then you will be asked for the XML file. There specify `robot.xml` (without anything else as the file is already in the working directory if you have moved the `set_ur5_joints.py` in the `include` directory). What should happen is that the `robot.xml` file is updated (quaternions of the UR5 bodies to reflect the desired joint angles).

Hope this helps.

**Comment by gokceay** [comment]
yes, I also want to do the same, change the body quaternions. The script worked :) thanks a lot, now I will try to change to code according to my model.xml
Have a nice day

**Comment by rpapallas** [comment]
Great, glad that this work is useful to you. Good luck with what you are doing!
